# Site Settings
site_name: How2.Red
copyright:  © 2025 | @How2Red


home_cover_image: how2/site/images/How2_Logo.png
home_tagline: Welcome to How2Red
home_description: |
  Try. Fail. Learn. Try Again. Get Better.



### STOLE FROM McCANN
# Custom Homepage Button(s)
home_button1_name: Red Cell   # Comment this parameter out to remove the button.
home_button1_url: Red Cell/   # This path starts at your root mkdocs directory.
home_button1_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people     # Options: "people", "gear", "image"
home_button1_blurb: |         # Short description of this button / section.
  Dive into the Red Cell for techniques surrounding Pentesting, Ethical Hacking, and Red Teaming.

home_button2_name: Test_Button # Comment this parameter out to remove the button.
home_button2_url: Recon/ # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Navigate through the Green Cell for insights into Infrastructure, DevOps, and IT operations.

home_button3_name: Test_Button  # Comment this parameter out to remove the button.
home_button3_url: Exploitation/  # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Explore the Blue Cell for Cybersecurity defense and threat analytics.

### END OF STEALING










theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md
  - Recon: recon/index.md
  - Exploitation: exploitation/index.md
  - Post-Exploitation: post-exploitation/index.md
  - Tips & Tricks: tips/index.md
