# Site Settings
site_name: How2Red
site_url: https://how2.red
copyright:  © 2025 | @How2Red

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
  logo: images/How2_Logo.png

extra_css:
  - css/style.css  # 👈 add it here

nav:
  - Home: index.md
  - Enumeration: Enumeration/index.md
  - Lateral Movement: Lateral_Movement/index.md
  - Privilege Escalation: Privilege_Escalation/index.md
  - Tips & Tricks: tips/index.md
