# Site Settings
site_name: How2Red
site_url: https://how2.red
copyright:  © 2025 | @How2Red

docs_dir: vault

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy
  logo: images/How2_Logo.png

extra_css:
  - css/style.css  # 👈 add it here

nav:
  - Home: index.md
  - Windows:
      - Windows/index.md
      - Active Directory:
          - Windows/Active Directory/index.md
          - DCSync: Windows/Active Directory/DCSync/index.md
          - DCSync Backdoor: Windows/Active Directory/DCSync Backdoor/index.md
      - Privilege Escalation: Windows/Privilege Escalation/index.md
  - Linux:
      - Linux/index.md
  - Test:
      - Test/index.md

extra:
  generator: false

plugins:
  - search

# Ensure CNAME is copied during builds
extra_files:
  - CNAME

